services:
  eshopdb:
    container_name: eshopdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=EShopDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_eshopdb:/var/lib/postgresql/data/
  
  seq:
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    restart: always
    ports:
      - "5341:5341"
      - "9091:80"
  
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=eshopdb;Port=5432;Database=BasketDb;User Id=postgres;Password=postgres;Include Error Detail=true
      - ASPNETCORE_URLS=https://+:${ASPNETCORE_HTTPS_PORT:-8081};http://+:${ASPNETCORE_HTTP_PORT:-8080}
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/https/aspnetapp.pfx
      - ConnectionStrings__Redis=distributedcache:6379
      - MessageBroker__Host=amqp://ecommerce-mq:5672
      - MessageBroker__UserName=guest
      - MessageBroker__Password=guest
      - Keycloak__AuthServerUrl=http://identity:9090/
      - Serilog__Using__0=Serilog.Sinks.Console
      - Serilog__Using__1=Serilog.Sinks.Seq
      - Serilog__MinimumLevel__Default=Information
      - Serilog__MinimumLevel__Override__Microsoft=Information
      - Serilog__MinimumLevel__Override__System=Warning
      - Serilog__WriteTo__0__Name=Console
      - Serilog__WriteTo__1__Name=Seq
      - Serilog__WriteTo__1__Args__serverUrl=http://seq:5341
      - Serilog__Enrich__0=FromLogContext
      - Serilog__Enrich__1=WithMachineName
      - Serilog__Enrich__2=WithProcessId
      - Serilog__Enrich__3=WithThreadId
      - Serilog__Properties__Application=EShop ASP.NET Core App
      - Serilog__Properties__Environment=Development
    depends_on:
      - eshopdb
    ports:
      - "6000:8080"
      - "6060:8081"
    volumes:
      - /Users/jose.padilla/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - /Users/jose.padilla/ASP.NET/Https:/app/https:ro