services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: src/Bootstrapper/API/Dockerfile
  
  eshopdb:
    image: postgres
  
  messagebus:
    image: rabbitmq:4.0.4-management

  seq:
    image: datalust/seq:2024.3
  
  distributedcache:
    image: redis
    
volumes:
  postgres_eshopdb: