version: '3.4'

services:
  api:
    image: api
    build:
      context: .
      dockerfile: src/Bootstrapper/API/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 8081:8081
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
